[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
perp = "XpJ2J8tahL9bf5Y6L4DCdj5oPBvtTAmo6uF8REuvrkm"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
